[workspace]
authors = ["AleWang16 <awang21913@gmail.com>"]
channels = ["conda-forge"]
name = "OpenScholar"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11.6"
numpy = "==1.26.4"
pytorch = ">=2.10.0,<3"
faiss-gpu = "==1.8.0"
omegaconf = ">=2.3.0,<3"
hydra-core = "==1.3.2"
tqdm = ">=4.67.3,<5"
transformers = "==4.39.3"
sentence-transformers = "==3.2.0"
openjdk = "==21.0.10"
pyarrow = "==20.0.0"
datasketch = ">=1.9.0,<2"
pyserini = ">=1.4.0,<2"
