cname: scaling
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pyarrow=20.*
  - openjdk=21
  - pytorch
  - faiss-gpu=1.8.0
  - pip
  - pip:
    - omegaconf
    - hydra-core
    - tqdm
    - transformers
    - sentence_transformers
    - pyserini
    - datasketch
