name: scaling
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pytorch
  - faiss-gpu=1.8.0
  - omegaconf
  - hydra-core=1.3
  - tqdm
  - transformers
  - sentence-transformers
  - pyserini
  - datasketch
  - openjdk=21
  - pyarrow=20
prefix: /home/awang/miniconda3/envs/scaling
